export const TOOL_PROMPTS: Record<string, string> = {
  blur: `This is a privacy protection task applied to a real photograph. Carefully scan the entire image and detect every human face present — including partially visible faces, faces at various angles, faces in the background, and faces that are small or far from the camera. For each detected face region, apply a strong, smooth Gaussian blur that completely obscures all facial features: eyes, nose, mouth, skin texture, and identifying details. The blur should be dense enough to make the face entirely unrecognizable, with soft edges that blend naturally into the surrounding area without any harsh boundaries or visible artifacts. The blurred region must cover the full face including forehead, chin, cheeks, and ears. Every other element of the image must remain completely untouched and pixel-perfect — the background, clothing, hair, body, hands, objects, colors, lighting, shadows, depth of field, and overall composition must be preserved exactly as they appear in the original.`,

  mosaic: `This is a privacy protection task applied to a real photograph. Carefully scan the entire image and detect every human face present — including partially visible faces, faces at various angles, faces in the background, and faces that are small or far from the camera. For each detected face region, apply a pixelated mosaic censorship effect using clearly visible square pixel blocks. The blocks should be large enough (roughly 10–15 pixels per block) to make the face completely unrecognizable, creating a classic digital-censorship appearance with clean, straight-edged pixel boundaries. The mosaic must cover the complete face area from forehead to chin and ear to ear, with no facial features bleeding through. Every other element of the image must remain completely untouched and pixel-perfect — the background, clothing, hair, body, hands, objects, colors, lighting, shadows, and overall composition must be preserved exactly as they appear in the original.`,

  emoji: `This is a privacy protection task applied to a real photograph. Carefully scan the entire image and detect every human face present — including partially visible faces, faces at various angles, faces in the background, and faces that are small or far from the camera. For each detected face, place a single large emoji precisely centered over the face, sized to fully cover the entire face from forehead to chin and ear to ear. Choose a naturally friendly emoji — such as 😊, 🙂, or 😄 — that suits the mood of the image. Render the emoji as a clean, flat, crisp overlay at full opacity so that no facial features are visible underneath. The emoji must look intentional and cleanly composited, not distorted, stretched, or transparent. Every other element of the image must remain completely untouched and pixel-perfect — the background, clothing, hair, body, hands, objects, colors, lighting, shadows, and overall composition must be preserved exactly as they appear in the original.`,

  auto: `This is a privacy protection task applied to a real photograph. Carefully scan the entire image and detect every human face present — including partially visible faces, faces at various angles, faces in the background, and faces that are small or far from the camera. For each detected face, automatically choose and apply the single most appropriate privacy-concealing technique based on the visual context of the image: smooth Gaussian blur for natural or portrait photographs, pixelated mosaic for formal or document-style images, and emoji overlay for casual or social-media-style images. Whichever technique is selected, it must completely and convincingly obscure all facial features so the person is entirely unrecognizable, while appearing professionally executed and intentional. Every other element of the image must remain completely untouched and pixel-perfect — the background, clothing, hair, body, hands, objects, colors, lighting, shadows, and overall composition must be preserved exactly as they appear in the original.`,
}

export function buildPrompt(tool: string | null, userText: string): string {
  const base = TOOL_PROMPTS[tool ?? ''] ?? TOOL_PROMPTS.auto
  return userText.trim() ? `${base} Additional instructions: ${userText.trim()}` : base
}
